---

# Set director paths for httpd and custome tools.
data_root:    "/data"
www_dir:      "{{ data_root }}/www"
tools_dir:    "{{ data_root }}/tools"
kernel_dir:   "{{ data_root }}/kernel"
bin_dir:      "{{ data_root }}/bin"
rpmbuild_dir: "{{ data_root }}/rpmbuild"
squashfs_dir: "{{ data_root }}/squashfs"
source_dir:   "{{ data_root }}/source"

# Set parameter for httpd
http_server_name: "local"
http_port: "80"

# Set srpm2html shells
srpm2html_shells:
    - url: "https://raw.githubusercontent.com/Noppy/mytools/master/srpm2html/srpm_to_html.sh"
    - url: "https://raw.githubusercontent.com/Noppy/mytools/master/srpm2html/kernel_srpm_to_html.sh"

# for making gnu global
global_version:   "global-6.5.6"
source_build_dir: "/tmp"
gnu_global_tar_url: "ftp://ftp.gnu.org/pub/gnu/global/{{ global_version }}.tar.gz"
check_global_file_path: "/usr/local/bin/htags"

# EBS device name in AWS
ebs_dev_name: "/dev/xvdb"
partition_dev_name: "{{ ebs_dev_name }}1"
