---
# file: /roles/httpd/tasks/customize_httpd.yml
# This playbook customizes the apache httpd server

- name: create additional content directories for httpd server
  file:
    path:  "{{ item }}"
    state: directory
    owner: apache
    group: apache
    mode:  0775
    seuser: "system_u"
    setype: "httpd_sys_content_t"
  notify: restart httpd
  with_items:
    - "{{ tools_dir }}"
    - "{{ kernel_dir }}"

- name: copy configuration files in conf.d/ directory
  copy:
    src:   "{{ item }}"
    dest:  "/etc/httpd/conf.d/{{ item }}"
    owner: "root"
    group: "root"
    mode:  0644
  notify: restart httpd
  with_items:
    - "kernels.conf"
    - "tools.conf"

