---
# file: /roles/common/tasks/main.yml
# This playbook deploys the apache httpd server

- name: install python2
  include: install-pkg-RedHat-dnf.yml
  when: "ansible_pkg_mgr == 'dnf'"
  tags:
    - install_python2

