---

# file: roles/common/tasks/main.yml
# 全サーバで設定が必要な項目のrole
#


- name: Bootstrap a host without python2 installed
  raw: dnf install -y python python-dnf libselinux-python python-firewall
  tags:
    - common-python
# comment-
# python            :Required by ansible.
# python-dnf        :Required by dnf module.
# libselinux-python :Required, if SELinux enabled on remote nodes.
# python-firewall   :Required by firewall module.
